services:
  - type: web
    name: multi-utility-ai-chatbot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --chdir backend_python app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
